[package]
name = "date-math"
version = "0.1.0"
authors = ["Josh Clayton <joshua.clayton@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
nom = "6"
structopt = "0.3"
